#!/usr/bin/env zsh
#
# Wrapper around `task` to use it as a challenge manager for the yearly
# "Booklord Challenge" in TBB.
#
# Each year of challenges is represented as a project, "challenge$YEAR".
# Individual tasks are challenges to be completed.
# Annotate a challenge with information about how it was completed; mark it
# "done" when finished.

source $(dirname $(realpath $0))/tasklib.sh

export TASKRC=$HOME/Books/booklordrc
export YEAR=$(date +%Y)

function main {
  task/init-config booklord.defaults \
    "context.$YEAR=project:challenge$YEAR" \
    "context=$YEAR"
  task/dispatch "$@"
}

task/register add-challenge '^add-challenge' booklord/-add-challenge <<EOF
EOF
function booklord/-add-challenge {
  shift
  COUNT=$(\task count)
  \task rc.dateformat:"Y-M-D H:N:S" add \
    project:"challenge${YEAR}" entry:"${YEAR}-01-01 00:${COUNT}:00" "$@"
}

# TODO: advance the year
# Need to:
# - mark all pending tasks for the current year deleted
# - run gc
# - task config context.ytd project:challenge${YEAR}

exec main "$@"
