#!/usr/bin/env zsh
#
# Command to open a URL from weechat in a smart way.
# For images, assume that we're connected from a terminal that supports
# kitty rasters, and invoke timgallery to temporarily detach from tmux
# and view the image.
# For other URLs, emit a custom OSC sequence that will be interpreted by
# the client machine as a command to open that URL.
# Earlier versions of this which I should recover from backups sometime
# worked by ssh'ing into the client machine to remotely open the browser,
# and earlier versions still by splitting the tmux display and using elinks/
# timg -- sadly a lot of the web is now unviewably in elinks.

# Walk up the process tree until we run out of processes or find something
# with stdout connected to something other than devnull
# tmux list-clients -F '#{client_activity} #{client_tty}' | sort -g | tail -n1 | cut -d' ' -f2
# If we're inside tmux, this will return the pty associated with the connected client
# that was most recently active, i.e. the one the user is sitting in front of
function find-tty {
  local pid=$$
  while [[ $pid != 1 ]]; do
    cat /proc/$pid/stat | read pid comm stat ppid _
    if [[ $(readlink /proc/$pid/fd/1) != /dev/null ]]; then
      echo -n "$pid"
      return
    fi
    pid=$ppid
  done
  echo "Error: couldn't find parent process with valid stdout" >&2
  echo -n "self"
}

function osc {
  local pid=$(find-tty)
  if [[ $TMUX ]]; then
    printf '\x1BPtmux;\x1B\x1B]%s\x07\x1B\\' "$*" > /proc/$pid/fd/1
  else
    printf '\x1B]%s\x07' "$*" > /proc/$pid/fd/1
  fi
}

# TODO: detect if the oscwrapper is connected (somehow?) and open locally if it's not,
# using split-window and elinks for links or tiv/timg for images.
function open-image {
#  osc "451;IMG;$1"
#  tmux split-window -h -c ~ zsh -c "source .zsh/aliases.zsh; timg '$1'"
  # this needs to be -ps if we're connected from yaft,
  # but -pk for konsole or kitty
  # todo: use split-window instead now that tmux supports sixel
  tmux detach -E "trap 'tmux attach' EXIT; timgallery -pa '$1'"
}

function open-video {
  osc "451;VID;$1"
}

function open-url {
  osc "451;URL;$1"
}

# Probe the URL to figure out what it is
# Ideally we'd use HEAD but a bunch of servers just 405 that???
content_type="$(curl -s -L --write-out "%{http_code}:%{content_type}" --output /dev/null "$1")"
if [[ $content_type != 200:* ]]; then
  # We used to do nothing here, but cloudflare bullshit means a lot of sites will
  # return 403 or whatnot to curl specifically :<
  open-url "$1"
elif [[ $content_type == 200:image/* ]]; then
  open-image "$1"
elif [[ $content_type == 200:video/* ]]; then
  open-video "$1"
else
  open-url "$1"
fi
